---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: governor-operator-role
rules:
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - governor.io
  resources:
  - governorroutes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - governor.io
  resources:
  - governorroutes/status
  verbs:
  - get
  - patch
  - update
